#!/bin/bash

# MAI Advisor - HuggingFace Space Deployment Script
# Run this to prepare files for upload

set -e

echo ""
echo "╔══════════════════════════════════════════════════════════╗"
echo "║                                                          ║"
echo "║     MAI ADVISOR - HUGGINGFACE SPACE DEPLOYMENT          ║"
echo "║                                                          ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""

# Check if we're in the right directory
if [ ! -f "app_workflow.py" ]; then
    echo "❌ Error: app_workflow.py not found!"
    echo "   Please run this script from mai-advisor-mcp/mai-advisor-mcp/"
    exit 1
fi

echo "✅ Found app_workflow.py"
echo ""

# Create deployment directory
DEPLOY_DIR="huggingface_space_deploy"
echo "📁 Creating deployment directory: $DEPLOY_DIR"
rm -rf "$DEPLOY_DIR"
mkdir -p "$DEPLOY_DIR"

# Copy essential files
echo ""
echo "📋 Copying files for HuggingFace Space..."
echo ""

echo "  ✓ README.md (hackathon version)"
cp README.md "$DEPLOY_DIR/"

echo "  ✓ app_workflow.py (main application)"
cp app_workflow.py "$DEPLOY_DIR/"

echo "  ✓ requirements.txt"
cp requirements.txt "$DEPLOY_DIR/"

echo "  ✓ LICENSE"
cp LICENSE "$DEPLOY_DIR/"

echo "  ✓ src/ directory"
cp -r src "$DEPLOY_DIR/"

echo "  ✓ .env.example (for documentation)"
cp .env.example "$DEPLOY_DIR/" 2>/dev/null || echo "  ⚠ .env.example not found (optional)"

echo ""
echo "╔══════════════════════════════════════════════════════════╗"
echo "║                  DEPLOYMENT READY! ✅                    ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""
echo "Files prepared in: $DEPLOY_DIR/"
echo ""
echo "📦 Files ready for upload:"
ls -lh "$DEPLOY_DIR"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo "NEXT STEPS:"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "1️⃣  Join HuggingFace Organization (if not done)"
echo "   → https://huggingface.co/MCP-1st-Birthday"
echo "   → Click 'Request to join this org'"
echo ""
echo "2️⃣  Create New Space"
echo "   → Go to: https://huggingface.co/new-space"
echo "   → Owner: MCP-1st-Birthday"
echo "   → Space name: mai-advisor-grant-planning"
echo "   → License: MIT"
echo "   → SDK: Gradio"
echo "   → Visibility: Public ⚠️  MUST BE PUBLIC!"
echo "   → Hardware: CPU basic (free)"
echo ""
echo "   ⚠️  DO NOT enable authentication!"
echo "   ⚠️  DO NOT make it private!"
echo "   ⚠️  Users provide their own API keys in the interface!"
echo ""
echo "3️⃣  Upload Files (via Web UI or Git)"
echo "   → Upload all files from: $DEPLOY_DIR/"
echo ""
echo "   Required files:"
echo "     • README.md (with hackathon tags!)"
echo "     • app_workflow.py"
echo "     • requirements.txt"
echo "     • src/ (entire directory)"
echo "     • LICENSE"
echo ""
echo "4️⃣  Wait for Build & Test"
echo "   → Build takes ~5-10 minutes"
echo "   → Space will be PUBLIC - no login required"
echo "   → Users provide their own OpenRouter API key"
echo "   → Test complete workflow"
echo "   → Verify all tabs work"
echo "   → Check downloads"
echo ""
echo "5️⃣  Update README with Links (AFTER deployment)"
echo "   → Add your demo video link"
echo "   → Add your social media post links"
echo "   → Update Space URL references"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo "📝 IMPORTANT REMINDERS:"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "✅ README.md has correct tags:"
echo "   - mcp-in-action-track-enterprise"
echo "   - building-mcp-track-enterprise"
echo ""
echo "⚠️  SPACE MUST BE PUBLIC - NO AUTHENTICATION!"
echo "    Users provide their own OpenRouter API keys"
echo "    NO HuggingFace Secrets/Environment Variables needed!"
echo ""
echo "⚠️  DO NOT add OPENROUTER_API_KEY to Space Secrets!"
echo "    Users enter their own keys in the Gradio interface!"
echo ""
echo "⚠️  DO NOT upload .env file!"
echo "    The .env.example is for local development only!"
echo ""
echo "⚠️  AFTER Space is live, add these to README:"
echo "    - Demo video link (line 30)"
echo "    - Social post links (line 28)"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "🎬 NEXT: Record your demo video"
echo "   See HACKATHON_CHECKLIST.md for video script"
echo ""
echo "Ready to deploy! 🚀"
echo ""
